edition = "2024"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
group_imports = "StdExternalCrate"
normalize_doc_attributes = true
format_strings = true
imports_granularity = "Crate"

# Unstable features below
# unstable_features = true
# version = "Two"
# comment_width = 100             # default is 80
# error_on_line_overflow = true
# format_code_in_doc_comments = true
# format_macro_bodies = true
# format_macro_matchers = true
