name: CI
on:
  push:
    branches: [ master ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      toolchain: stable

  test:
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      toolchain: stable

  clippy:
    needs: build
    uses: ./.github/workflows/lint.yml
    with:
      toolchain: stable

  fmt:
    needs: build
    uses: ./.github/workflows/fmt.yml
    with:
      toolchain: stable

  sbom:
    needs: [build]
    uses: ./.github/workflows/sbom.yml
