name: CI
on:
  push:
    branches: [ master ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./build.yml
    with:
      toolchain: stable

  test:
    needs: build
    uses: ./test.yml
    with:
      toolchain: stable

  clippy:
    needs: build
    uses: ./lint.yml
    with:
      toolchain: stable

  fmt:
    needs: build
    uses: ./fmt.yml
    with:
      toolchain: stable

  sbom:
    needs: [build]
    uses: ./sbom.yml
