name: Fmt
on:
  workflow_call:
    inputs:
      toolchain:
        type: string
        default: stable
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@${{ inputs.toolchain }}
        with:
          components: rustfmt
      - name: Fmt check
        run: cargo fmt --all -- --check
